spring:
  profiles:
    active: local
    include: oauth
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
jwt:
  secret-key: himynameiskimjihunmyyoutubechann
  # 1시간 (ms)
  accessTokenExpiresIn: 3600000
  # 7일 (ms)
  refreshTokenExpiresIn: 604800000

logging:
  level:
    root: INFO
    com.denticheck.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
