spring:
    profiles:
        active: local
        include: oauth, secret
    graphql:
        graphiql:
            enabled: true
        schema:
            printer:
                enabled: true
jwt:
    secret-key: himynameiskimjihunmyyoutubechann
    accessTokenExpiresIn: 1h
    refreshTokenExpiresIn: 30d
    enable-development-tokens: false

logging:
    level:
        root: INFO
        com.denticheck.api: DEBUG
        # org.hibernate.SQL: DEBUG
    # pattern:
    #     console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID:-} --- [%thread] %logger{36} : %msg%n"

springdoc:
    api-docs:
        path: /docs/api-docs
    swagger-ui:
        path: /docs/swagger-ui
        disable-swagger-default-url: true
